import Head from 'next/head'
import { useEffect, useState } from 'react'
import { ethers } from 'ethers'
import styles from '../styles/Home.module.css'
import { connectToContract, getAccount, getProviderSigned } from '../utils/ethers'
import Token from '../artifacts/contracts/Token.sol/Token.json';


export default function Home() {

  const [contract, setContract] = useState();
  const [supply, setSupply] = useState();
  const [balance, setBalance] = useState();

  useEffect(async () => {
    const contract = await connectToContract();
    setContract(contract);
    _getSupply(contract);
    _getBalance(contract);
  }, []);
  
  async function _getSupply(contract) {
    const totalSupply = await contract.totalSupply();
    setSupply(ethers.utils.formatUnits(totalSupply, 0));
  } 
  
  async function _getBalance(contract) {
    const account = await getAccount();
    const balanceOfUser = await contract.balanceOf(account);
    setBalance(ethers.utils.formatUnits(balanceOfUser, 0));
  }

  async function _transfer() {
    const contract = await getProviderSigned();
    const transaction = await contract.transfer(
      '0x4bD23e98d0D492536F2e84630aDEbE2Fd01AFBc2', 
      "2500"
    );
    await transaction.wait();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Bubble Token!</a>
        </h1>
        <p>Supply is : {supply}</p>
        <p>My balance is : {balance} </p>
        <div className='mt-5'>
          <button onClick={() => _transfer()}className='bg-green-500 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded-full m-auto'>Transfer</button>
        </div>
      </main>
    </div>
  )
}
